### ISSUE TITLE
PerfGraph Live Not Quite Right With MultiApp Setup

### ISSUE THREAD

**Issue by friedmud** [idaholab/moose#19114]
## Bug Description
@aprilnovak reported that she is seeing intertwining prints during multiapp setup:

```
Creating MultiApp bison of type CardinalApp of level 1 and number 0:
bison0:
bison0: Setting Mesh
bison0:   Finished Reading Mesh                                                                  [  8.18 s] [  882 MB]
bison0: Finished Setting Mesh                                                                    [  8.18 s] [  882 MB]
Still Setting Upbison0:
bison0:     Updating Mesh
bison0:       Finished Building Boundary Elements List                                           [  1.11 s] [  137 MB]
.bison0:     Finished Updating Mesh                                                               [  7.28 s] [  481 MB]
bison0:   Finished Preparing Mesh                                                                [  9.05 s] [  481 MB]
bison0: Finished Setting Up Undisplaced Mesh                                                     [  9.05 s] [  481 MB]
................bison0: Initializing
  Updating Because Mesh Changed
    Finished Updating Mesh                                                               [  7.61 s] [    3 MB]
bison0:   Finished Updating Because Mesh Changed                                                 [  7.91 s] [   45 MB]
..bison0: .                                                         [ 10.76 s] [ 4378 MB]
bison0: Finished Initializing                                                                    [ 18.69 s] [ 4423 MB]

  Initializing
    Updating Because Mesh Changed
      Finished Updating Mesh                                                             [  9.30 s] [   41 MB]
    Finished Updating Because Mesh Changed                                               [  9.61 s] [  107 MB]
    Finished Initializing Equation Systems                                               [  6.96 s] [ 1424 MB]
  Finished Initializing                                                                  [ 16.59 s] [ 1531 MB]
Finished Setting Up                                                                      [345.93 s] [11090 MB]
```

## Steps to Reproduce
It looks like all that is necessary is a particularly long time used to setup a sub-app.

## Impact
Just bad screen output

**Comment by friedmud** [comment]
This should give back similar capability to what you could get with `CONTROLLED_CONSOLE_TIMED_PRINT` with a time of `0`

**Comment by friedmud** [comment]
This was fixed in https://github.com/idaholab/moose/pull/20907

**Comment by GiudGiud** [comment]
Still not quite right
```
ns0: Initializing
  Finished Initializing Equation Systems                                                 [  4.56 s] [  253 MB]
ns0: Finished Initializing                                                                    [  4.60 s] [  279 MB]
```
I think we want to re-add the multiapp prefix when doing a "finished"

**Comment by GiudGiud** [comment]
Another instance
```
Setting Up
  Uniformly Refining.....
    Updating Mesh                                                                        [  8.52 s] [  247 MB]
  Finished Uniformly Refining                                                            [ 45.57 s] [ 2224 MB]
Creating MultiApp sub of type MooseTestApp of level 1 and number 0 on processor 0 with full name sub0
sub0: Uniformly Refining.....
sub0:   Updating Mesh                                                                          [  8.34 s] [  248 MB]
sub0: Finished Uniformly Refining                                                              [ 44.63 s] [ 2192 MB]
sub0: Initializing
  Updating Because Mesh Changed
    Updating Mesh                                                                        [  9.19 s] [    0 MB]
sub0:   Finished Updating Because Mesh Changed                                                 [ 10.03 s] [   69 MB]
sub0:   Initializing Equation Systems...                                                       [ 28.88 s] [ 1629 MB]
sub0: Finished Initializing                                                                    [ 38.92 s] [ 1699 MB]
Creating MultiApp sub of type MooseTestApp of level 1 and number 1 on processor 0 with full name sub1
sub1: Uniformly Refining.....
sub1:   Updating Mesh                                                                          [  8.39 s] [  248 MB]
sub1: Finished Uniformly Refining                                                              [ 44.57 s] [ 2190 MB]
sub1: Initializing
  Updating Because Mesh Changed
    Updating Mesh                                                                        [  9.25 s] [    0 MB]
```

Here we d want:
- dont forget prefix on "updating" prints
- add the spacing on the main app output too, to align with the subapp
