### ISSUE TITLE
Problem with mesh adaptivity and stateful variables (in PorousFlow)

### ISSUE THREAD

**Issue by WilkAndy** [idaholab/moose#7625]
### Description of the enhancement or error report

Tagging @cpgr, and asking for help from @permcody .

I cannot use mesh adaptivity in PorousFlow.  This could be related to #7116.  I don't think I have the skill or the time to track this down.  I get errors such as:

```
Process 27787 stopped
* thread #1: tid = 0x14c83f, 0x000000010139b707 libmoose-dbg.0.dylib`shallowCopyData(stateful_prop_ids=0x000000010666e610, data=0x00000001063ac688, data_from=0x0000000107bcdf10) + 167 at MaterialPropertyStorage.C:37, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010139b707 libmoose-dbg.0.dylib`shallowCopyData(stateful_prop_ids=0x000000010666e610, data=0x00000001063ac688, data_from=0x0000000107bcdf10) + 167 at MaterialPropertyStorage.C:37
   34     for (unsigned int i=0; i<stateful_prop_ids.size(); ++i)
   35     {
   36       PropertyValue * prop = data[stateful_prop_ids[i]];              // do the look-up just once (OPT)
-> 37       PropertyValue * prop_from = data_from[i];                       // do the look-up just once (OPT)
   38       if (prop != NULL && prop_from != NULL)
   39         prop->swap(prop_from);
   40     }

```
### Rationale for the enhancement or information for reproducing the error

You may reproduce the error by running the test file

modules/porous_flow/tests/convection/convect_1d.i

in debug mode and using Adaptivity (remove the active = '' line in that file)
### Identified impact

(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

**Comment by permcody** [comment]
I'm not convinced that #7116 is your problem. You might try it once more after the fix is merged though.

**Comment by WilkAndy** [comment]
This is still a problem: the above input file crashes with adaptivity, bummer.

**Comment by WilkAndy** [comment]
This is still a problem.  The input file has been renamed and is now:

porous_flow/tests/heat_advection/heat_advection_1d.i

remove the active = '' line in that file and you'll get a nice seg fault.
