### ISSUE TITLE
DebugResidualAux segfaults on CONSTANT MONOMIAL variables

### ISSUE THREAD

**Issue by dschwen** [idaholab/moose#7800]
### Description of the enhancement or error report
```
[Debug]
  show_var_residual = 'v'
[]
```

where `v` is a constant monomial variable causes a segfault in opt and triggers `libmesh_assert_less (comp, this->n_comp(s,var));` in `libMesh::DofObject::dof_number(this=[...], s=0, var=1, comp=0) const` 

### Rationale for the enhancement or information for reproducing the error
It's a bug. I'll push a simple commit to demonstrate this below.

### Identified impact
Makes residual debugging harder.

**Comment by DanielYankura** [comment]
When running your test case I got an error which was added in this PR #14020. The only other case I've seen where `DebugResidualAux` segfaults with a constant monomial should be resolved with #29920 so once that one is merged I think this issue can be closed.

**Comment by GiudGiud** [comment]
I verified that constant monomials are no longer an issue

I raised #30444 for the variable types for which we still have an issue
