### ISSUE TITLE
Contact Verification test unstable with 64-bit indices

### ISSUE THREAD

**Issue by permcody** [idaholab/moose#8200]
### Description of the enhancement or error report

The contact_verification/patch_tests/cyl_3.mu_0_2_kin fails quite often with the error message "Unable to find nearest node" on the 64-bit index target. It might just mean that this test is just barely on the verge of passing as is and the extra memory footprint of this build sometimes triggers this failure. It'd be nice to get this cleaned up.

### Rationale for the enhancement or information for reproducing the error

contact_verification/patch_tests/cyl_3.mu_0_2_kin fails sometimes with 64-bit

### Identified impact
(i.e. Internal object changes, limited interface changes, public API change, or a list of specific applications impacted)

Unknown impact, may just be a flaky test.

**Comment by permcody** [comment]
Tag @acasagran?

**Comment by acasagran** [comment]
The mesh in this test is two QUAD8 elements aligned in the vertical direction. All of the nodes should have a nearest neighbor at the same position.

**Comment by brianmoose** [comment]
This seems to always fail with PETSc 3.7.4
and is reproducible on the mac with the latest package.

**Comment by permcody** [comment]
@acasagran, @fdkong - I'm not sure where this ticket is on the priority list but we might consider disabling this test if it's going to be awhile. It's bad to a "normally red" box on the build status because then we don't look it anymore. I'd rather not accumulate any new regressions while this one is broken.

**Comment by brianmoose** [comment]
This also seems to happen reliably with Intel compiler, PETSc 3.7.4, and 32 bit dofs.
See https://www.moosebuild.org/job/61622/

**Comment by bwspenc** [comment]
This issue is broader than just cases where we're using 64-bit indices, and I don't think it really has anything to do with use of 64-bit indices.  We're seeing these "Unable to locate nearest node" errors on a variety of problems (that involve tensor_mechanics and contact) when we build with PETSc 3.7.4.  This error happens when we get a solution vector that contains nan or inf values.  It seems to be a problem with the version of SuperLU shipped with PETSc 3.7.4.

We're only seeing this in a few isolated cases in our regression tests, but we see it on almost every real BISON problem we try to run with PETSc 3.7.4 (when we use tensor_mechanics).  This doesn't seem to be tied to element type, as we see this in our 1D and 2D example problems.

 If nobody is opposed, I'd propose that we re-name this ticket to reflect the fact that we are broadly seeing erratic solver behavior with contact + tensor_mechanics + SuperLU + PETSc 3.7.4.

**Comment by bwspenc** [comment]
It's also worth noting that we've tested PETSc 3.7.5 and see the same issue.

**Comment by fdkong** [comment]
> This issue is broader than just cases where we're using 64-bit indices, and I don't think it really has anything to do with use of 64-bit indices. We're seeing these "Unable to locate nearest node" errors on a variety of problems (that involve tensor_mechanics and contact) when we build with PETSc 3.7.4. This error happens when we get a solution vector that contains nan or inf values. It seems to be a problem with the version of SuperLU shipped with PETSc 3.7.4.
> 
> We're only seeing this in a few isolated cases in our regression tests, but we see it on almost every real BISON problem we try to run with PETSc 3.7.4 (when we use tensor_mechanics). This doesn't seem to be tied to element type, as we see this in our 1D and 2D example problems.
> 
> If nobody is opposed, I'd propose that we re-name this ticket to reflect the fact that we are broadly seeing erratic solver behavior with contact + tensor_mechanics + SuperLU + PETSc 3.7.4.

@bwspenc, I am definitely happy to take a look into this ticket, if there are many related applications. @acasagran reproduced this issue using a very small problem a couple of weeks ago. We got a solution vector containing  nan or inf values, and there was a "Unable to locate nearest node" error. We have fixed the case from @acasagran. In my opinion,  this issue is related to the Jacobian, and the Jacobian matrix is not formed correctly. You could easily check the difference between the matrix obtained using finite difference and the one coded by hand.  If we are going to use the Jacobian calculated  by finite difference, and then superlu_dist does a  perfect job on the problem.  "volumetric locking" stuffs make the Jacobian even worse. If @acasagran turned off "volumetric locking", and the issue could be fixed.

The first thing we would  do is to "correct" the Jacobian, if possible.  The benefit of that is that we will have a more robust solver.  PETSc and SuperLU_dist are under intensively  developing, and unfortunately, two packages do not have backward compatibility.

**Comment by bwspenc** [comment]
@fdkong We see this same error on 1D problems where the is no volumetric locking correction, so I don't think this actually has anything to do with that.

We have a number of example BISON problems that fail reliably with 3.7.4 on Mac, but unfortunately, they're a little bit larger problems.  The smaller regression-style problems that use only MOOSE seem to only fail on Linux with 3.7.4.

**Comment by fdkong** [comment]
> @fdkong We see this same error on 1D problems where the is no volumetric locking correction, so I don't think this actually has anything to do with that.

@bwspenc,

Could you explicitly turn off the volumetric locking? 

> 
> We have a number of example BISON problems that fail reliably with 3.7.4 on Mac, but unfortunately, they're a little bit larger problems. The smaller regression-style problems that use only MOOSE seem to only fail on Linux with 3.7.4.

Could you make the problem smaller, and the check the Jacobian?

**Comment by bwspenc** [comment]
@fdkong Yes, we can turn off volumetric locking and check the Jacobian on those problems.  We will do that.  I still think there's a bug in that version of SuperLU though if it's that sensitive, since the built-in LU works without any issues.

**Comment by fdkong** [comment]
> @fdkong Yes, we can turn off volumetric locking and check the Jacobian on those problems. We will do that. I still think there's a bug in that version of SuperLU though if it's that sensitive, since the built-in LU works without any issues.

 Thanks, @bwspenc. If there are still issues after the Jacobian is improved, I will be taking a look into SuperLU_dist.  I thinking about to add a native parallel LU in PETSc, but unfortunately, we do not have funding to do so.

**Comment by permcody** [comment]
@fdkong - Perhaps this issue can be fully resolved? I didn't look but we should probably see if the test here can run with 64-bits again.

**Comment by permcody** [comment]
This has been resolved with PETSc. 3.7.6+.

**Comment by bwspenc** [comment]
As much as I'd love to close this, we still have 4 tests that are skipped because of this, and I thought that was because they were still failing with 64-bit indices.  Run git grep '#8200' to see those tests.

**Comment by fdkong** [comment]
I will check this, @bwspenc, @permcody.
